sudo: required

language: php

branches:
    only:
        - master
        - alpine

notifications:
    slack:
        secure: Six7p+nRQhZapzzZvHBi0WgsPDndm+PjqjqeDdCqbSRrCQz+h/nr828Iin6woqPIFdc7qXAXpVaoNyopntVsoGjzkWkwlFHXpBhv6+zHV+yE5S+HfD4IG5HGS+qQa35XebJ93cHZGPqxdjBWusoSFOuQBQuC7ohZ3KEeZTizV1w3qbzA7p94sxcz/w0zJw8liD+0CJ39U6hL0QGE1fpkqpb/muxjbjQOSeGLzzmd04Don37X/aUmwSBZbLUmqOjkQ7R4fRWcVNyqxDuLnHh56J+UIZ/xN/K43fI9mzBohxkWa5GQGQDHY1ojlJyOCcLLb+Q2cnjz8s+FfCY/iMcXQOgfZSc7gvpFBysSWNG7RuGlmvff5A+ufqhFGh2O2PRcAF3kPuCKna4RI84kzoybAXXrjRnvqmoLzY9OTL/OOd4WheCmdrx70eIDxW0COKbaSDnyjgbOM6Xk8/50QsGjKZ+1XqHvslV0jpksUKxPCgOxMTIzAngzGizunetT6RJ8JjUAkOrDnW9ntWca1czZxUeF0SLbkGy401tXpdPUwC+tgsI8aCf5+fgCQGa6sKu0p17Qe91c5dPjJEJprSzRERD4YRMxTvv+DBx1zUYvwxr1GaAUZexI3UgUybIvZOvBg+AmjW+/ayqCVv/d3Ct0OyAKY08Hp0/E1lvqg+seKyI=

services:
    - docker

before_install:
    - docker build -t mkenney/composer:travis-ci .
    - cd test

script:
    - docker run --rm -t -i -v $(pwd):/src:rw -v $HOME/.ssh:/home/dev/.ssh:ro mkenney/composer:travis-ci update
